/**
 * This file is autogenerated by helper.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/helper/contract";

const deployedContracts = {
  31337: {
    AuctionFactory: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          inputs: [],
          name: "ZamaProtocolUnsupported",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "auctionAddress",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "category",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "string",
              name: "itemTitle",
              type: "string",
            },
          ],
          name: "AuctionCreated",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "allAuctions",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "auctionCreators",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "confidentialProtocolId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_itemURI",
              type: "string",
            },
            {
              internalType: "string",
              name: "_itemTitle",
              type: "string",
            },
            {
              internalType: "string",
              name: "_itemDescription",
              type: "string",
            },
            {
              internalType: "address",
              name: "_paymentToken",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_durationSeconds",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "_category",
              type: "uint8",
            },
            {
              internalType: "address",
              name: "_nftContract",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_nftTokenId",
              type: "uint256",
            },
          ],
          name: "createAuction",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "getAllAuctions",
          outputs: [
            {
              internalType: "address[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getAuctionCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_auction",
              type: "address",
            },
          ],
          name: "getAuctionInfo",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "auctionAddress",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "creator",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "itemTitle",
                  type: "string",
                },
                {
                  internalType: "uint8",
                  name: "category",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "deadline",
                  type: "uint256",
                },
                {
                  internalType: "uint8",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "bidderCount",
                  type: "uint256",
                },
              ],
              internalType: "struct AuctionFactory.AuctionInfo",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "offset",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "limit",
              type: "uint256",
            },
          ],
          name: "getAuctionsPaginated",
          outputs: [
            {
              internalType: "address[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 3,
    },
  },
  11155111: {
    AuctionFactory: {
      address: "0xf6aACE498919826cFDbC8C3C125D6FCE161Ce39f",
      abi: [
        {
          inputs: [],
          name: "ZamaProtocolUnsupported",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "auctionAddress",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "category",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "string",
              name: "itemTitle",
              type: "string",
            },
          ],
          name: "AuctionCreated",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "allAuctions",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "auctionCreators",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "confidentialProtocolId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_itemURI",
              type: "string",
            },
            {
              internalType: "string",
              name: "_itemTitle",
              type: "string",
            },
            {
              internalType: "string",
              name: "_itemDescription",
              type: "string",
            },
            {
              internalType: "address",
              name: "_paymentToken",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_durationSeconds",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "_category",
              type: "uint8",
            },
            {
              internalType: "address",
              name: "_nftContract",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_nftTokenId",
              type: "uint256",
            },
          ],
          name: "createAuction",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "getAllAuctions",
          outputs: [
            {
              internalType: "address[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getAuctionCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_auction",
              type: "address",
            },
          ],
          name: "getAuctionInfo",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "auctionAddress",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "creator",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "itemTitle",
                  type: "string",
                },
                {
                  internalType: "uint8",
                  name: "category",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "deadline",
                  type: "uint256",
                },
                {
                  internalType: "uint8",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "bidderCount",
                  type: "uint256",
                },
              ],
              internalType: "struct AuctionFactory.AuctionInfo",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "offset",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "limit",
              type: "uint256",
            },
          ],
          name: "getAuctionsPaginated",
          outputs: [
            {
              internalType: "address[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 10704756,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
